version: '3.8'

services:
  # Service pour l'application .NET (Windows)
  dockerContainerApp:
    build:
      context: ./AuthApp  # Spécifie le répertoire de contexte du build
      dockerfile: Dockerfile  # Spécifie le fichier Dockerfile dans le répertoire
    ports:
      - "5000:80"  # Expose le port de l'application .NET
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mynetwork
    depends_on:
      - sqlserver  # L'application dépend du service SQL Server
    restart: always
    volumes:
      - ./app_data:/app/data  # Exemple de volume pour l'application .NET (si nécessaire)

  # Service pour SQL Server 2022 (Linux)
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA="Y"  # Accepte le contrat de licence
      - MSSQL_SA_PASSWORD="PWDAZERTYUIOP!"  # Mot de passe pour le compte SA
    ports:
      - "1433:1433"  # Port pour accéder à SQL Server
    networks:
      - mynetwork
    restart: always
    volumes:
      - sql_data:/var/opt/mssql  # Volume pour persister les données de SQL Server

networks:
  mynetwork:  # Réseau par défaut pour la communication entre les services

volumes:
  sql_data:  # Volume persistant pour SQL Server
